def listarProductos():
    print("lista de productos")
    print("1. coca cola")
    print("2. cheetos")
    print("3. maruchan")
    print("4. palomitas")
    print("5. gomitas")
    print("6. fruta")
    print("7. verdura")
    print("8. helado")
    print("9. papel higienico") 
    print("10. gansito ") 

def listaIngredientes():
    print("1-peperoni")
    print("2-champiñones")
    print("3-chorizo")
    print("4-jamon")
    print("5-piña")
    print("6-tocino")
    print("7-salchica")
    print("8-pimiento verde")
    print("9-aceitunas")
    print("10-salami")
    print("9-cebolla")
    print("10-jitomate")
    print("11-extra queso")
    print("12-atun")
    print("13-ajonjoli")
    print("14-moztaza")
    print("15-aguacate")
    print("16-jalapeños")
    print("17-pera")
    print("18-pollo")
    print("19-frijol")
    print("20-arandanos")
    print("21-arrachera")
    print("22-mozarela")
    print("23-gouda")
    print("24-carne molida")
    print("25-maiz")
    print("")


def listaTamanos():
    print("1-familiar")
    print("2-grande")
    print("3-mediana")
    print("4-chica")
    print("5-mini pizza")
    print("6-cuadrada") 
